server:
  port: 8081

spring:
  main:
    web-application-type: servlet


  datasource:
    url: ${DB_URL:jdbc:postgresql://aws-1-eu-west-3.pooler.supabase.com:6543/postgres}
    username: ${DB_USERNAME:postgres.qgwpbqwvopzmwluziade}
    password: ${DB_PASSWORD:PFAdatabaseLAAZEZ}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  jackson:
    serialization:
      write-dates-as-timestamps: false

# JWT Configuration
app:
  jwt:
    secret: PFA_ENIS_2026_SECRET_KEY_FOR_JWT_TOKEN_GENERATION_MUST_BE_AT_LEAST_256_BITS_LONG
    expiration-ms: 86400000  # 24 hours

  # AI Recommendation Engine URL
  ai-service:
    base-url: http://localhost:8000

  # File upload directory
  upload:
    dir: ./uploads

logging:
  level:
    com.pfa.elearning: DEBUG
    org.springframework.security: DEBUG
